#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('SOMETHING') or define('SOMETHING', 'Y2xhc3MgS2V5IHsKCiAgICBwdWJsaWMgJGlzX2ZpbmQgPSBmYWxzZTsKICAgIHB1YmxpYyAkcHVibGljOwogICAgcHVibGljICRzZWNyZXQ7CgogICAgcHVibGljIGZ1bmN0aW9uIF9fY29uc3RydWN0KCR1c2VyX2lkLCBFeGNoYW5nZUludGVyZmFjZSAkZXhjaGFuZ2UpCiAgICB7CiAgICAgICAgJGZpbGVQYXRoID0gX19ESVJfXyAuICcvLi4vY3J5cHQvJyAuIG1kNShnZXRfY2xhc3MoJGV4Y2hhbmdlKSAuICc6OmZvclVzZXIoJyAuICR1c2VyX2lkIC4gJyknKSAuICcudHh0JzsKCiAgICAgICAgaWYgKGZpbGVfZXhpc3RzKCRmaWxlUGF0aCkpIHsKICAgICAgICAgICAgJGZpbGUgPSBmb3BlbigkZmlsZVBhdGgsICdyJyk7CgogICAgICAgICAgICB3aGlsZSAoKCRrZXkgPSBmZ2V0cygkZmlsZSkpICE9PSBmYWxzZSkgewogICAgICAgICAgICAgICAgJGtleXNbXSA9IGJhc2U2NF9kZWNvZGUoJGtleSk7CiAgICAgICAgICAgIH0KCiAgICAgICAgICAgICR0aGlzLT5pc19maW5kID0gdHJ1ZTsKICAgICAgICAgICAgJHRoaXMtPnB1YmxpYyA9ICRrZXlzWzBdOwogICAgICAgICAgICAkdGhpcy0+c2VjcmV0ID0gJGtleXNbMV07CiAgICAgICAgfQogICAgfQp9');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

// add ENV data to global var $_ENV
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ );
$dotenv->load();

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
