#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('SOMETHING') or define('SOMETHING', 'Y2xhc3MgS2V5IHsKCiAgICBwdWJsaWMgJGlzX2ZpbmQgPSBmYWxzZTsKICAgIHB1YmxpYyAkcHVibGljOwogICAgcHVibGljICRzZWNyZXQ7CgogICAgcHVibGljIGZ1bmN0aW9uIF9fY29uc3RydWN0KCR1c2VyX2lkKQogICAgewogICAgICAgICRmaWxlUGF0aCA9ICcuL2NyeXB0LycgLiBtZDUoJHVzZXJfaWQpIC4gJy50eHQnOwoKICAgICAgICBpZiAoZmlsZV9leGlzdHMoJGZpbGVQYXRoKSkgewogICAgICAgICAgICAkZmlsZSA9IGZvcGVuKCRmaWxlUGF0aCwgJ3InKTsKCiAgICAgICAgICAgIHdoaWxlICgoJGtleSA9IGZnZXRzKCRmaWxlKSkgIT09IGZhbHNlKSB7CiAgICAgICAgICAgICAgICAka2V5c1tdID0gYmFzZTY0X2RlY29kZSgka2V5KTsKICAgICAgICAgICAgfQoKICAgICAgICAgICAgJHRoaXMtPmlzX2ZpbmQgPSB0cnVlOwogICAgICAgICAgICAkdGhpcy0+cHVibGljID0gJGtleXNbMF07CiAgICAgICAgICAgICR0aGlzLT5zZWNyZXQgPSAka2V5c1sxXTsKICAgICAgICB9CiAgICB9Cn0=');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

// add ENV data to global var $_ENV
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ );
$dotenv->load();

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
